defaultPlacement: end
enableVersioning: true
handle: generalPages
name: 'general pages'
propagationMethod: all
siteSettings:
  3298e2ac-f9f1-4685-b69c-448a7f44bb90: # Mototventure
    enabledByDefault: true
    hasUrls: true
    template: general.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: d1cfa65b-41e3-4c70-aa6b-d5915efc1170
type: structure
